---
- name: Check disks available on Linux servers
  hosts: dr-servers
  gather_facts: yes
  tasks:
    - name: Gather disk information using lsblk
      command: lsblk -f
      register: disk_info
      changed_when: false

    - name: Show simplified disk information
      debug:
        msg: "{{ item }}"
      with_items: "{{ disk_info.stdout_lines }}"
