---
- name: Display drive paths on Linux servers
  hosts: dr-servers
  gather_facts: no
  tasks:
    - name: Gather disk paths
      command: ll /dev/disk/by-path
      register: disk_info
      changed_when: false

    - name: Show disk paths
      debug:
        var: disk_info.stdout_lines
